"""Type definitions for the generator module.

The generator takes a FactsBundle and produces a Telegram-ready message.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Optional


class GenerationMode(Enum):
    """Run modes for message generation."""

    US_CLOSE = "us_close"
    WEEKEND_WRAP = "weekend_wrap"
    MONDAY_PREVIEW = "monday_preview"

    @classmethod
    def from_string(cls, mode: str) -> "GenerationMode":
        """Convert string to GenerationMode.

        Args:
            mode: Mode string (e.g., "us_close").

        Returns:
            Corresponding GenerationMode enum value.

        Raises:
            ValueError: If mode string is not recognized.
        """
        mode_map = {
            "us_close": cls.US_CLOSE,
            "weekend_wrap": cls.WEEKEND_WRAP,
            "monday_preview": cls.MONDAY_PREVIEW,
        }
        if mode not in mode_map:
            raise ValueError(f"Unknown generation mode: {mode}")
        return mode_map[mode]


@dataclass
class GeneratorConfig:
    """Configuration for the message generator.

    Attributes:
        enabled: Whether generation is enabled.
        model: OpenRouter model identifier (e.g., "openai/gpt-4.1").
        temperature: LLM temperature (0-1). Lower = more deterministic.
        max_retries: Number of retries on LLM failure.
        timeout_seconds: HTTP timeout for LLM API calls.
    """

    enabled: bool = True
    model: str = "openai/gpt-4.1"
    temperature: float = 0.4
    max_retries: int = 1
    timeout_seconds: int = 60


@dataclass
class LLMGeneratedContent:
    """Content generated by the LLM.

    This is the structured output from the LLM before final assembly.
    The LLM generates narrative text using [n] references to news items.
    """

    # Narrative paragraphs (2-6 paragraphs)
    narrative: str

    # Investor Key Takeaways (3-5 bullets)
    takeaways: list[str]

    # What to Watch Next (max 3 bullets)
    watch_next: list[str]

    # News item IDs that were referenced (in order of first reference)
    referenced_item_ids: list[int] = field(default_factory=list)

    # Raw LLM response for debugging
    raw_response: Optional[str] = None


@dataclass
class GeneratorResult:
    """Result from message generation.

    Contains the final formatted message and metadata about the generation.
    """

    # The final Telegram-ready message (MarkdownV2 escaped)
    message: str

    # The message before MarkdownV2 escaping (for debugging/validation)
    message_raw: str

    # Word count of the narrative portion
    word_count: int

    # Number of news items referenced
    sources_count: int

    # Whether spotlight was included
    has_spotlight: bool

    # Generation metadata
    model: str
    generation_mode: GenerationMode
    generated_at: datetime

    # Retry count (0 = first attempt succeeded)
    retry_count: int = 0

    # Duration of LLM call(s) in seconds
    llm_duration_seconds: float = 0.0

    # Error message if generation partially failed
    error: Optional[str] = None

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "message": self.message,
            "message_raw": self.message_raw,
            "word_count": self.word_count,
            "sources_count": self.sources_count,
            "has_spotlight": self.has_spotlight,
            "model": self.model,
            "generation_mode": self.generation_mode.value,
            "generated_at": self.generated_at.isoformat(),
            "retry_count": self.retry_count,
            "llm_duration_seconds": self.llm_duration_seconds,
            "error": self.error,
        }


@dataclass
class NewsContext:
    """Pre-processed news item context for the LLM.

    Each news item is assigned a reference number [1], [2], etc.
    The LLM uses these references in the narrative.
    """

    ref_number: int  # 1-based reference number
    news_item_id: int
    title: str
    source_name: str
    source_url: str
    published_date: Optional[str]  # Formatted date string
    snippet: Optional[str]
    content_excerpt: Optional[str]
    topic: Optional[str]

    def format_for_prompt(self) -> str:
        """Format this news item for inclusion in LLM prompt.

        Returns:
            Formatted string for the prompt.
        """
        content = self.content_excerpt or self.snippet or "(no content)"
        # Truncate content to avoid overly long prompts
        if len(content) > 500:
            content = content[:497] + "..."

        topic_str = f" [{self.topic}]" if self.topic else ""
        date_str = f" ({self.published_date})" if self.published_date else ""

        return f"""[{self.ref_number}] {self.title}
Source: {self.source_name}{date_str}{topic_str}
Content: {content}"""

    def format_for_sources(self, display_number: int | None = None) -> str:
        """Format this news item for the Sources section.

        Args:
            display_number: Override the reference number for display.
                           If None, uses the original ref_number.

        Returns:
            Formatted source citation string with hyperlink.
        """
        num = display_number if display_number is not None else self.ref_number
        return f"[{num}] [{self.title}]({self.source_url})"
